import { NextPage, GetStaticProps, GetStaticPaths } from 'next'
import Head from 'next/head'
import { getPost, getSlugs } from '../../utils/post'
import Markdown from 'react-markdown'
import { Me } from '../../components/Me'
import { Copy } from '../../components/Copy'
import { CodeBlock } from '../../components/CodeBlock'

type StaticPaths = {
  slug: string
}

type StaticProps = {
  post: Post
}

const PostPage: NextPage<StaticProps> = (props) => {
  const { post } = { ...props }
  return (
    <>
      <Head>
        <title>
          {post.metadata.title} - お前もインターネットにしてやろうか
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-6xl flex justify-center mt-10 mb-10">
        {post.metadata.emoji}
      </div>
      <h1 className="text-5xl font-bold mt-10 italic leading-tight">
        {post.metadata.title}
      </h1>
      <div className="underline-red mt-4 text-sm font-bold italic">
        {post.metadata.createdAt}
      </div>
      <div className="markdown mt-10 leading-relaxed">
        <Markdown
          components={{
            code({ inline, className, children }) {
              const match = /language-(\w+)/.exec(className || '')
              return !inline && match ? (
                <CodeBlock
                  language={match[1]}
                  value={children.toString().replace(/\n$/, '')}
                />
              ) : (
                <code className={className}>{children}</code>
              )
            },
          }}
        >
          {post.content}
        </Markdown>
      </div>
      <Me />
      <Copy />
    </>
  )
}

// /md/配下のmarkdownファイル名を取得し、ファイル名をslugにする
export const getStaticPaths: GetStaticPaths<StaticPaths> = async () => {
  const slugs = await getSlugs()
  return {
    paths: slugs.map((slug) => ({
      params: {
        slug: slug,
      },
    })),
    fallback: false,
  }
}

// markdownのメタデータ記法部分を変換してPropsにする
export const getStaticProps: GetStaticProps<StaticProps, StaticPaths> = async (
  context,
) => {
  const slug = context.params?.slug!
  const post = await getPost(slug)
  return {
    props: {
      post,
    },
  }
}

export default PostPage
