import { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import React from 'react'
import { Card } from '../components/Card'
import { sortAndFilterPosts } from '../utils/sortAndFilter'
import { getPostWithSlug, getSlugs } from '../utils/post'
import { generateRss } from '../utils/rss'
import { useTab } from '../components/Tab'

type StaticProps = {
  posts: PostWithSlug[]
}

const HomePage: NextPage<StaticProps> = (proprs) => {
  const { selected, onClick, tab } = useTab()
  return (
    <>
      <Head>
        <title>asazutaiga.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://pbs.twimg.com/profile_images/1606963603336482817/S498lmc__400x400.jpg"
          type="image/jpeg"
        />
      </Head>
      <div className="mt-10 flex flex-col gap-4">
        {tab}
        <div className="flex flex-col gap-4">
          {proprs.posts.map(
            (post) =>
              (selected === 'all' || post.metadata.genre === selected) && (
                <Card post={post} key={post.slug} />
              ),
          )}
        </div>
      </div>
    </>
  )
}

export default HomePage

export const getStaticProps: GetStaticProps<StaticProps> = async () => {
  const slugs = await getSlugs()
  const posts = await Promise.all(slugs.map((slug) => getPostWithSlug(slug)))
  const sortedAndFiltered = sortAndFilterPosts(posts)

  // 記事一覧を取得したタイミングで、RSSフィードも生成しておく
  generateRss(sortedAndFiltered)

  return {
    props: {
      posts: sortedAndFiltered,
    },
  }
}
