import { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import { Card } from '../components/Card'
import { Container } from '../components/Container'
import { Copy } from '../components/Copy'
import { Me } from '../components/Me'
import { sortPostsByDate } from '../utils/date'
import { getPostWithSlug, getSlugs } from '../utils/post'

type StaticProps = {
  posts: PostWithSlug[]
}

const HomePage: NextPage<StaticProps> = (proprs) => {
  return (
    <>
      <Head>
        <title>お前もインターネットにしてやろうか</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-10" />
      {proprs.posts.map((post) => (
        <>
          <div className="h-3" />
          <Card post={post} key={post.slug} />
          <div className="h-3" />
        </>
      ))}
      <div className="h-10" />
      <Me />
      <Copy />
    </>
  )
}

export default HomePage

export const getStaticProps: GetStaticProps<StaticProps> = async () => {
  const slugs = await getSlugs()
  const posts = await Promise.all(slugs.map((slug) => getPostWithSlug(slug)))
  const sortedPosts = sortPostsByDate(posts)
  return {
    props: {
      posts: sortedPosts,
    },
  }
}
