import { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import React from 'react'
import { Card } from '../components/Card'
import { sortAndFilterPosts } from '../utils/sortAndFilter'
import { getPostWithSlug, getSlugs } from '../utils/post'
import { generateRss } from '../utils/rss'
import { useTab } from '../components/Tab'
import { Transition } from '@headlessui/react'

type StaticProps = {
  posts: PostWithSlug[]
}

const HomePage: NextPage<StaticProps> = (proprs) => {
  const { selected, tab } = useTab()
  return (
    <>
      <Head>
        <title>asazutaiga.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://pbs.twimg.com/profile_images/1606963603336482817/S498lmc__400x400.jpg"
          type="image/jpeg"
        />
      </Head>
      <div className="mt-10 flex flex-col gap-4">
        {tab}
        <Transition
          show={selected === 'all'}
          enterFrom="mt-4 opacity-50"
          enterTo="mt-0 opacity-100"
          enter="transition-all duration-300"
        >
          <div className="flex flex-col gap-4">
            {proprs.posts.map((post) => (
              <Card post={post} key={post.slug} />
            ))}
          </div>
        </Transition>
        <Transition
          show={selected === 'tech'}
          enterFrom="mt-4 opacity-50"
          enterTo="mt-0 opacity-100"
          enter="transition-all duration-300"
        >
          <div className="flex flex-col gap-4">
            {proprs.posts
              .filter((post) => post.metadata.genre === 'tech')
              .map((post) => (
                <Card post={post} key={post.slug} />
              ))}
          </div>
        </Transition>
        <Transition
          show={selected === 'life'}
          enterFrom="mt-4 opacity-50"
          enterTo="mt-0 opacity-100"
          enter="transition-all duration-300"
        >
          <div className="flex flex-col gap-4">
            {proprs.posts
              .filter((post) => post.metadata.genre === 'life')
              .map((post) => (
                <Card post={post} key={post.slug} />
              ))}
          </div>
        </Transition>
      </div>
    </>
  )
}

export default HomePage

export const getStaticProps: GetStaticProps<StaticProps> = async () => {
  const slugs = await getSlugs()
  const posts = await Promise.all(slugs.map((slug) => getPostWithSlug(slug)))
  const sortedAndFiltered = sortAndFilterPosts(posts)

  // 記事一覧を取得したタイミングで、RSSフィードも生成しておく
  generateRss(sortedAndFiltered)

  return {
    props: {
      posts: sortedAndFiltered,
    },
  }
}
